galaxy_info:
  author: Felix Hartmond, Michael Eder
  description: Certbutler is used to obtain wildcard LetsEncrypt certificates
  company: HvS-Consulting AG

  license: GPLv3

  min_ansible_version: 2.4

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Debian
    versions:
    - all
