---
# tasks file for certbutler-ansible
- name: 'Create certbutler directories'
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: '/etc/certbutler/' }
    - { path: '/etc/certbutler/certificates' }
    - { path: '/etc/certbutler/configurations' }

- name: 'Copy certbutler configuration'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'certbutler.service.j2', dest: '/etc/systemd/system/certbutler.service', mode: '0644'}
    - { src: 'certbutler.timer.j2', dest: '/etc/systemd/system/certbutler.timer', mode: '0644'}
    - { src: 'certbutler', dest: '/usr/local/bin/certbutler', mode: '0755'} # You need to provide a certbutler binary
    - { src: 'certbutler_yoursite.com.yml.j2', dest: '/etc/certbutler/configurations/certbutler_yoursite.com.yml', mode: '0644'}
  notify: 'Enable certbutler timer'
